[package]
name = "keepawake"
version = "0.1.3"
authors = ["Segev Finer <segev208@gmail.com>"]
edition = "2021"
rust-version = "1.63"
description = "Keep your computer awake"
repository = "https://github.com/segevfiner/keepawake-rs/"
license = "MIT"
keywords = ["caffeinate", "systemd-inhibit", "idle", "sleep", "power-management"]
categories = ["command-line-utilities"]
exclude = ["/tools/"]

[profile.release]
strip = true
lto = "thin"

[dependencies]
anyhow = "1.0.65"
cfg-if = "1.0.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.43.0"
features = [
    "Win32_System_Power"
]

[target.'cfg(target_os = "linux")'.dependencies]
zbus = "3.1.0"

[target.'cfg(target_os = "macos")'.dependencies]
apple-sys = { version = "0.1.2", features = ["CoreFoundation", "IOKit"] }
core-foundation = "0.9.3"

[build-dependencies]
shadow-rs = "0.17.0"
winres = "0.1.12"
